# Generated by Django 4.0.1 on 2022-01-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Przykładowa rzecz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttype',
            name='color',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='size',
            field=models.SlugField(),
        ),
    ]
