# Generated by Django 4.0.1 on 2022-01-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='item_type',
        ),
    ]
