# Generated by Django 4.0.1 on 2022-01-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_order_created_orderposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
