# Generated by Django 4.0.1 on 2022-01-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_item_name_availability_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='color',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
