# Generated by Django 4.0.1 on 2022-01-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_producttype_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderposition',
            name='availability',
        ),
    ]
