# Generated by Django 4.0.1 on 2022-01-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_orderposition_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
