# Generated by Django 4.0.1 on 2022-01-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_delete_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderposition',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.producttype'),
            preserve_default=False,
        ),
    ]
