# Generated by Django 4.0.1 on 2022-01-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_orderposition_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
