# Generated by Django 4.0.1 on 2022-01-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_producttype_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderposition',
            name='product',
        ),
    ]
